Repository AbeGue02/tick-it, pull requests merged in 2024-03, with the labels that each got.

#6 Adds React Screens to work on
  front-end/tick-it/index.html
  front-end/tick-it/src/App.css
  front-end/tick-it/src/App.jsx
  front-end/tick-it/src/components/Header.jsx
  front-end/tick-it/src/components/Main.jsx
  front-end/tick-it/src/index.css
  front-end/tick-it/src/main.jsx
  front-end/tick-it/src/screens/EventDetails.jsx
  front-end/tick-it/src/screens/EventList.jsx
  front-end/tick-it/src/screens/Home.jsx
  front-end/tick-it/src/screens/VenueDetails.jsx
  front-end/tick-it/src/screens/VenueList.jsx
Labels: Feature, React

#7 3 add serializers to django
  back-end/Pipfile
  back-end/Pipfile.lock
  back-end/tickit/migrations/0001_initial.py
  back-end/tickit/models.py
  back-end/tickit/serializers.py
  back-end/tickit/urls.py
  back-end/tickit/views.py
  back-end/tickit_django/urls.py
Labels: Feature, Django

#12 10 create a django seeding file
  back-end/.gitignore
  back-end/seed.sql
  back-end/seed_data.py
  back-end/tickit/__pycache__/__init__.cpython-312.pyc
  back-end/tickit/__pycache__/admin.cpython-312.pyc
  back-end/tickit/__pycache__/apps.cpython-312.pyc
  back-end/tickit/__pycache__/models.cpython-312.pyc
  back-end/tickit/__pycache__/serializers.cpython-312.pyc
  back-end/tickit/__pycache__/urls.cpython-312.pyc
  back-end/tickit/__pycache__/views.cpython-312.pyc
  back-end/tickit/migrations/__pycache__/0001_initial.cpython-312.pyc
  back-end/tickit/migrations/__pycache__/__init__.cpython-312.pyc
  back-end/tickit_django/__pycache__/__init__.cpython-312.pyc
  back-end/tickit_django/__pycache__/settings.cpython-312.pyc
  back-end/tickit_django/__pycache__/urls.cpython-312.pyc
  back-end/tickit_django/__pycache__/wsgi.cpython-312.pyc
  back-end/tickit_django/settings.py
Labels: Feature, Django

#13 Scott
  back-end/tickit/__pycache__/models.cpython-312.pyc
  back-end/tickit/__pycache__/serializers.cpython-312.pyc
  back-end/tickit/__pycache__/urls.cpython-312.pyc
  back-end/tickit/__pycache__/views.cpython-312.pyc
  back-end/tickit/serializers.py
  back-end/tickit_django/__pycache__/settings.cpython-312.pyc
  front-end/package-lock.json
  front-end/tick-it/src/screens/VenueList.jsx
  package-lock.json
Labels: Django, Improvement

#14 Adds EventListItems component and styles
  front-end/tick-it/src/App.css
  front-end/tick-it/src/assets/80s_background.png
  front-end/tick-it/src/assets/synth_city_background.jpg
  front-end/tick-it/src/components/EventListItem.jsx
  front-end/tick-it/src/components/Header.jsx
  front-end/tick-it/src/components/Main.jsx
  front-end/tick-it/src/components/SearchBar.jsx
  front-end/tick-it/src/screens/EventList.jsx
Labels: Feature, React

#19 Makes SearchBar component work
  front-end/tick-it/src/components/SearchBar.jsx
  front-end/tick-it/src/screens/EventList.jsx
Labels: React, Improvement

#22 Header styling
  front-end/tick-it/src/App.css
  front-end/tick-it/src/components/Header.jsx
Labels: React, Improvement

#23 Scott
  front-end/tick-it/src/assets/Screenshot 2024-03-27 at 2.15.09 PM.png
  front-end/tick-it/src/components/VenueListItem.jsx
  front-end/tick-it/src/screens/EventDetails.jsx
  front-end/tick-it/src/screens/EventList.jsx
  front-end/tick-it/src/screens/VenueDetails.jsx
  front-end/tick-it/src/screens/VenueList.jsx
Labels: React, Improvement

#27 checkout
  front-end/tick-it/src/assets/EasterEgg.png
  front-end/tick-it/src/components/Checkout.jsx
  front-end/tick-it/src/components/Main.jsx
  front-end/tick-it/src/screens/EventDetails.jsx
Labels: React, Improvement

#29 Add final stylings
  front-end/tick-it/src/App.css
  front-end/tick-it/src/screens/EventDetails.jsx
  front-end/tick-it/src/screens/Home.jsx
Labels: React, Improvement
